### PR TITLE
Fixed: Now Numbering project was changed to Numbering within current module only.

### PR DESCRIPTION
**Pull request by hustbeef**

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
I do not agree with this, if you want to add, add a new menu item.

**Comment by hustbeef** [comment]
The  numbering the whole project is terrible output message and useless. It is better changed to Numbering within current module only.  The user can numbering one by one module if they have to do.

**Comment by XusinboyBekchanov** [comment]
The numbering of the project as before should be left only in the Edit -> Error Handling menu item and remove from Toolbar.

**Comment by hustbeef** [comment]
OK. That's good idea. I agrre. Just add a sub about module numbering and keep the old one

**Comment by XusinboyBekchanov** [comment]
Ok

**Comment by hustbeef** [comment]
Now the numbering of the project as before  only in the Edit -> Error Handling menu item and remove from Toolbar.

**Comment by XusinboyBekchanov** [comment]
Thanks.

**Pull request merged**
