### PR TITLE
Fixed: Showing the index and the count of finding

### PR DESCRIPTION
**Pull request by hustbeef**

### CODE REVIEW

**Comment by hustbeef** [comment]
How can I center the selected item of a listview within the visible area?

**Comment by chunmingwang** [comment]
Should i reopen the Suggestions for finding and replacing ?
https://github.com/XusinboyBekchanov/VisualFBEditor/issues/552

**Comment by chunmingwang** [comment]
Hi XiaLin, 
I Download your finding, experience was great, and some issues were found:

*. Form display issue: 

image

image

*. Replace issue: After replacing, the positioning jumps to the next two and should be positioned to the next one.

**Comment by hustbeef** [comment]
Yes. the code working. ListView_EnsureVisible(plvSearch->Handle, jj, True) 
Should we add this code to the property ? (Private Property ListView.SelectedItemIndex(Value As Integer))
The above bugs will be fixed soon.

**Comment by XusinboyBekchanov** [comment]
>Yes. the code working. ListView_EnsureVisible(plvSearch->Handle, jj, True)
>Should we add this code to the property ? (Private Property ListView.SelectedItemIndex(Value As Integer))

I added.

Added: EnsureVisible method to ListView:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/9f7a15a80f69ed8b3875d31623167ad8a887a1bb

**Comment by XusinboyBekchanov** [comment]
>Add the code " ListView_EnsureVisible(Handle, Value, True)" there also?

Added.

Added: EnsureVisible method to ListView on Linux:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/7aa01ccdcadb41536c2323b3e61c15ab1fd927d5

**Comment by XusinboyBekchanov** [comment]
Your replacement method is a little slower on large files, for example check TabWindow.bas. Because when replacing, it searches for all occurrences each time.

**Comment by hustbeef** [comment]
We can improve the speed for this. But It is very  impotant that  showing the count and remove the buttom FindAll.

**Comment by hustbeef** [comment]
XusinboyBekchanov, Fixed: replacement method is a little slower on large files. Yes, it is better use the code "Find True" to skip some finding. That could  jumping from  item 5 to item 10 of 24 items

**Comment by XusinboyBekchanov** [comment]
It's not good to miss it, let it be as before

**Comment by hustbeef** [comment]
Missing what? no missinng!

**Comment by XusinboyBekchanov** [comment]
Ok.

**Pull request merged**
