### PR TITLE
Remove unused procedure

### PR DESCRIPTION
**Pull request by hustbeef**

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
You are also removing ExtraMargins. See how it was before, how it is now. Now all the borders of the Options Window are clear.

**Comment by hustbeef** [comment]
Yes, the value of ExtraMargins is not oK and the control missing.

**Comment by hustbeef** [comment]
All the borders of the Options Window are clear now.

**Comment by XusinboyBekchanov** [comment]
>Yes, the value of ExtraMargins is not oK and the control missing.
Fixed: Showing ComboBoxEdit:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/92ac93c617f7b75bb9a7abfb5dae9ff982fa9e8f

**Pull request closed without merging**
