### PR TITLE
Update gdipClock Example

### PR DESCRIPTION
**Pull request by chunmingwang**
Happy Dragon Year and New Year

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
Thanks.

**Comment by hustbeef** [comment]
Not suitable for high DPI screens. You will notice the difference when you change your screen DPI to 200% and run the program.
image

**Comment by chunmingwang** [comment]
Thanks.

> Thanks.

Noticed, i will check it out later.

> Not suitable for high DPI screens. You will notice the difference when you change your screen DPI to 200% and run the program.

**Comment by chunmingwang** [comment]
> Thanks.
> 
> > Thanks.
> 
> Noticed, i will check it out later.
> 
> > Not suitable for high DPI screens. You will notice the difference when you change your screen DPI to 200% and run the program.

https://github.com/XusinboyBekchanov/VisualFBEditor/pull/603

**Pull request merged**
