### PR TITLE
Add 3 bass examples

### PR DESCRIPTION
**Pull request by chunmingwang**
1, bassaudio - audio play back, sound recoder, network raido, and sound effects, Waveform, EQ, spectrum, etc
2, livefx - audio live input/output effects
3, netradio - network raido

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
Thanks for the examples.

**Comment by XusinboyBekchanov** [comment]
Can't compile LiveFX, throws the following error:
17:32:49: Compilation: "F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\fbc32.exe"  -b "frmLiveFX.frm" -exx -v -x ".\release32\livefx32.exe" "frmLiveFX.rc" -s console -i "F:\Install\Install2\VisualFBEditor/./MyFbFramework"

FreeBASIC Compiler - Version 1.09.0 (2021-12-31), built for win32 (32bit)

Copyright (C) 2004-2021 The FreeBASIC development team.

standalone

target:       win32, 486, 32bit

backend:      gas

compiling:    frmLiveFX.frm -o frmLiveFX.asm (main module)

assembling:   F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\bin\win32\as.exe --32 --strip-local-absolute "frmLiveFX.asm" -o "frmLiveFX.o"

compiling rc:               F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\bin\win32\GoRC.exe /ni /nw /o /fo "frmLiveFX.obj" "frmLiveFX.rc"

linking:      F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\bin\win32\ld.exe -m i386pe -o ".\release32\livefx32.exe" -subsystem console -T "F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\lib\win32\fbextra.x" --stack 1048576,1048576 -s -L "F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\lib\win32" -L "." "F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\lib\win32\crt2.o" "F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\lib\win32\crtbegin.o" "F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\lib\win32\fbrt0.o" "frmLiveFX.o" "frmLiveFX.obj" "-(" -lkernel32 -lgdi32 -lmsimg32 -luser32 -lversion -ladvapi32 -limm32 -lcomctl32 -lcomdlg32 -luuid -lole32 -loleaut32 -liphlpapi -lrasapi32 -lws2_32 -lshlwapi -lshell32 -lddraw -ldxguid -lgdiplus -luxtheme -lbass -lfbmt -lgcc -lmsvcrt -lmingw32 -lmingwex -lmoldname -lgcc_eh "-)" "F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\lib\win32\crtend.o" 

F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\bin\win32\ld.exe: frmLiveFX.o:fake:(.text+0x33b30): undefined reference to `BASS_ChannelGetLevelEx'

linking failed: 'F:\Install\Install2\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\bin\win32\ld.exe' terminated with exit code 1


17:32:54: Do not build file. Elapsed Time: 4,72 Seconds

Do you compile?

**Comment by chunmingwang** [comment]
Because the bass Library of fbc 1.09.0 is relatively old and no BASS_ChannelGetLevelEx function in it.
Please copy the attached file to fbc\lib

[lib.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/8496369/lib.zip)

**Comment by chunmingwang** [comment]
Here is my compile result and screenshot just now

```
 22:29:50: Compilation: "F:\OfficePC_Update\!FB\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\fbc32.exe"  -b "frmLiveFX.frm" -exx -v -x ".\release32\livefx32.exe" "frmLiveFX.rc" -s gui -i "F:\OfficePC_Update\!FB\!VisualFBEditor\VisualFBEditor/./MyFbFramework"

FreeBASIC Compiler - Version 1.09.0 (2021-12-31), built for win32 (32bit)

Copyright (C) 2004-2021 The FreeBASIC development team.

standalone

target:       win32, 486, 32bit

backend:      gas

compiling:    frmLiveFX.frm -o frmLiveFX.asm (main module)

assembling:   F:\OfficePC_Update\!FB\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\bin\win32\as.exe --32 --strip-local-absolute "frmLiveFX.asm" -o "frmLiveFX.o"

compiling rc:               F:\OfficePC_Update\!FB\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\bin\win32\GoRC.exe /ni /nw /o /fo "frmLiveFX.obj" "frmLiveFX.rc"

linking:      F:\OfficePC_Update\!FB\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\bin\win32\ld.exe -m i386pe -o ".\release32\livefx32.exe" -subsystem windows -T "F:\OfficePC_Update\!FB\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\lib\win32\fbextra.x" --stack 1048576,1048576 -s -L "F:\OfficePC_Update\!FB\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\lib\win32" -L "." "F:\OfficePC_Update\!FB\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\lib\win32\crt2.o" "F:\OfficePC_Update\!FB\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\lib\win32\crtbegin.o" "F:\OfficePC_Update\!FB\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\lib\win32\fbrt0.o" "frmLiveFX.o" "frmLiveFX.obj" "-(" -lkernel32 -lgdi32 -lmsimg32 -luser32 -lversion -ladvapi32 -limm32 -lcomctl32 -lcomdlg32 -luuid -lole32 -loleaut32 -liphlpapi -lrasapi32 -lws2_32 -lshlwapi -lshell32 -lddraw -ldxguid -lgdiplus -luxtheme -lbass -lfbmt -lgcc -lmsvcrt -lmingw32 -lmingwex -lmoldname -lgcc_eh "-)" "F:\OfficePC_Update\!FB\FreeBASIC-1.09.0-winlibs-gcc-9.3.0\lib\win32\crtend.o" 


22:29:53: Layout succeeded! Elapsed Time: 2.09 Seconds
22:29:53: Run: "livefx32.exe"   ...
22:29:56: Application finished. Returned code: 0 - No error

```

untitle

**Comment by XusinboyBekchanov** [comment]
Thanks,

Works great!

**Pull request merged**
