### PR TITLE
Fixed: Disable "Form" button when edit code file

### PR DESCRIPTION
**Pull request by hustbeef**

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
If you automatically close the right panel, then why do you need a pin button? In my opinion, it is not necessary to automatically close, this interferes with the normal functioning of the pin button.

**Comment by hustbeef** [comment]
For "*.bas" file no need showing the forms and codeForms  button but it is neccessary  optional for "*.frm" file.  It is important for small size screen like 11in or 13inn laptop.

**Comment by XusinboyBekchanov** [comment]
In this case, you can also press the pin button.

**Comment by hustbeef** [comment]
If TAB selection change from "*.frm" to "*.bas" file. You have to click the button. This function to minimize the click. That's why it is importannt for the user like me working with small size screen.

**Comment by XusinboyBekchanov** [comment]
Ok

**Pull request merged**
