### PR TITLE
Fixed: Hide events that begin with the "._" prefix in the drop-down list

### PR DESCRIPTION
**Pull request by hustbeef**

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
Why hide what is there?

**Comment by hustbeef** [comment]
Hide the static events which begin with the "._" prefix in the drop-down list and will not hide the one end with "_".

**Comment by hustbeef** [comment]
"Declare Static Sub _cmdBtn_Click(ByRef Sender As Control)".  it will not showing in the cbofunction if you uncheck in setting windows .  "Declare Static Sub cmdBtn_Click_(ByRef Sender As Control)".  it will showing in the cbofunction.  This is the ruler of IDE for minimize the items count of cbofunction.

**Comment by hustbeef** [comment]
Fixed the DotBar not showing when compile with fbc1.10 with GCC -O3 now. the code now is working

**Comment by XusinboyBekchanov** [comment]
Merged. Thanks.

**Pull request merged**
