### PR TITLE
added online ci to build binaries for linux x86 bit

### PR DESCRIPTION
**Pull request by graysuit**
It will build and upload the binaries. 
With just little modifcation, you can also build for windows, linux with different architectures. 

It will trigger build whenever any file is changed or pull request created.

### CODE REVIEW

**Comment by graysuit** [comment]
sorry, actually this uploads x64 release, NOT x86. lol

**Comment by XusinboyBekchanov** [comment]
I fixed: https://github.com/XusinboyBekchanov/VisualFBEditor/commit/3d5c41f348ec44081727b8f1ff1752f87adf31b3

**Comment by graysuit** [comment]
No this isn't fix.
The current ubuntu VM is **x64**. But **fbc x86** won't run.
See fbc can't run : https://github.com/XusinboyBekchanov/VisualFBEditor/runs/3209611681?check_suite_focus=true#step:4:416
and also binary wasn't compiled nor uploaded.

I recommend revert changes. Instead, I guess [`-target <os>-<arch>`](https://www.freebasic.net/wiki/CompilerOpttarget) will help. 
But in my case, I wasn't successful.

**Comment by XusinboyBekchanov** [comment]
I returned to its previous state

**Pull request merged**
