### PR TITLE
Fixed: Corrected compilation error in Main.bas output in local language

### PR DESCRIPTION
**Pull request by hustbeef**

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
No, you need to add the following line to the lng file:
```Found $1. = ```
When updating the lng file, this line is automatically added.
This is because different languages may have different word order. Needed for this.

**Comment by hustbeef** [comment]
This translates only the word "Found". (ML(“Found”)). It is not the complete parameter. How to show the Russia words "Found" in output windows?

**Comment by hustbeef** [comment]
So there is no conflict after adding ML. No need to add the line "Found $????. =" to the lng file.

**Comment by XusinboyBekchanov** [comment]
>This translates only the word "Found". (ML(“Found”)). It is not the complete parameter. How to show the Russia words "Found" in output windows?

https://github.com/XusinboyBekchanov/VisualFBEditor/commit/db726825fce94a3dfe1ee84c6de888400d444358

Like this:
image

**Pull request closed without merging**
