### PR TITLE
Update Find & Replace

### PR DESCRIPTION
**Pull request by chunmingwang**
1. Change mFormFind from public shared to frmFind private
2. Change Layout
3. Change btnReplaceShow_Click 
4. Add chkBox_Click

image

image

### CODE REVIEW

**Comment by hustbeef** [comment]
Yes. We can accept the change ad could be reverse the code if it is not the best one.  We have to recove the code from my version in sub  frmFind.btnFind_Click and frmFind.btnFindPrev_Click because it not workig in find and replace in Project files. "Find True" only working in a single file.

**Comment by chunmingwang** [comment]
> Yes. We can accept the change ad could be reverse the code if it is not the best one. We have to recove the code from my version in sub frmFind.btnFind_Click and frmFind.btnFindPrev_Click because it not workig in find and replace in Project files. "Find True" only working in a single file.

Sure, It's too complicated, I didn't make any changes to frmFind.btnFind_ Click and frmFind.btnFindPrev_ Click

**Comment by XusinboyBekchanov** [comment]
>Yes. We can accept the change ad could be reverse the code if it is not the best one. We have to recove the code from my version in sub frmFind.btnFind_Click and frmFind.btnFindPrev_Click because it not workig in find and replace in Project files. "Find True" only working in a single file.

You can restore the previous code, taking into account the new changes.

**Comment by chunmingwang** [comment]
This PR, It is a change based on the latest code

**Comment by hustbeef** [comment]
1. No need to add the  sub Add chkBox_Click
2. The font Webdings included in all versions of  Microsoft Windows. But I am not sure it is OK in other OS Linnux
3. Change mFormFind from public shared to frmFind private. It is trouble if the font Webdings not working

**Comment by XusinboyBekchanov** [comment]
When I'm near Linux I'll take a look, otherwise I'll put a Unicode character.

**Comment by hustbeef** [comment]
Item 1: Add chkBox_Click, OK.  Meaing apply the change at once.

**Comment by chunmingwang** [comment]
> 3. Change mFormFind from public shared to frmFind private. It is trouble if the font Webdings not working

Sorry, my finally it's change mFormFind from public shared to frmFind public, it still can access by frmFind member.
Too many global variables can easily be confused and cause confusion.

> When I'm near Linux I'll take a look, otherwise I'll put a Unicode character.

That will be greate for both Windows/Linux

**Comment by hustbeef** [comment]
image
This is the finding layout of Github.
image
This is the finding layout of Vscode.
So, it is not necessary to change the layout that requires a special font.

**Comment by XusinboyBekchanov** [comment]
Ok, send a pull-request for your option

**Pull request merged**
