### PR TITLE
Update MDI Notepad Example

### PR DESCRIPTION
**Pull request by chunmingwang**
1. Update icons
2. Improve Toolbar
3. Others improve

### CODE REVIEW

**Comment by hustbeef** [comment]
image
I still got the warning about rc files.

**Comment by XusinboyBekchanov** [comment]
Fixed: RC file compiles once in MDINotepad Example:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/f3496661903ddadf604bebb11f11957022336bc3

**Comment by hustbeef** [comment]
The title bar and toolbar not refresh immediately after change to dark mode. 
It happens before in IDE and It's time to move those code from IDE to MyFbFramework.
image

**Comment by XusinboyBekchanov** [comment]
>The title bar and toolbar not refresh immediately after change to dark mode.

Are you compiling without a manifest?

>It happens before in IDE and It's time to move those code from IDE to MyFbFramework.

What code? This is because you are compiling without a manifest.

**Comment by hustbeef** [comment]
I compile the code from the Examples\MDINotepad.

**Comment by XusinboyBekchanov** [comment]
You are compiling without a manifest, right?
image

**Comment by hustbeef** [comment]
Yes. It is.

**Comment by hustbeef** [comment]
It is not compile with manifest file even the Manifest checkbox is on in project property windows.

**Comment by XusinboyBekchanov** [comment]
Why doesn't it compile? What error does it give?

**Comment by hustbeef** [comment]
I think there is a bug in function compile.
image

image

image

**Comment by XusinboyBekchanov** [comment]
Update TabWindow.bas:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/76e20cc37a2e299fc3ded4e87625d19bd074f26d

Now check Manifest and try compiling.

**Comment by hustbeef** [comment]
The title bar not refesh immediately and toolbar refresh after change to dark mode. Annd this time compile with rc file this time. and can not change the ICON file in project property windows.

Is it happen in my computer only? Should is the same errors showing!


image

**Comment by chunmingwang** [comment]
here is my screenshot, no such issue.

无图  (2)

**Comment by hustbeef** [comment]
The toolbar of MenuEditor is not a white background color in OS Windows XP & Windows 7.  Also this happen in Windows 10 after switch on/off darkmode. 

image

**Comment by XusinboyBekchanov** [comment]
Fixed: Menu Editor coloring:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/992cbadfde3b6d00cab2e6f9109a11c43752a5a4

**Comment by chunmingwang** [comment]
Working on Hash, File Search and File Sync...
Preview as following

**Comment by XusinboyBekchanov** [comment]
Good.

**Pull request merged**
