### PR TITLE
Added: Locale support for Examples in MDIForm

### PR DESCRIPTION
**Pull request by hustbeef**
Expect these examples to be runnable on Linux.

### CODE REVIEW

**Comment by hustbeef** [comment]
Yes. Expect all these examples to be runnable on Linux. On Linux. MDI forms can be implemented using GTK. These toolkits provide features similar to MDI form in Windows, allowing developers to implement similar user interface designs on the Linux platform.

**Comment by chunmingwang** [comment]
> Yes. Expect all these examples to be runnable on Linux. On Linux. MDI forms can be implemented using GTK. These toolkits provide features similar to MDI form in Windows, allowing developers to implement similar user interface designs on the Linux platform.

if then, try to do that

**Comment by XusinboyBekchanov** [comment]
Thanks.

**Comment by XusinboyBekchanov** [comment]
>is mdi form work on Linux？

Some work has been done to support MDI Child in Linux, for example, a form in MDI Child mode uses GtkBox and GtkHeaderBar.

**Pull request merged**
