### PR TITLE
Added:  Implemented checks for resource file keywords.

### PR DESCRIPTION
**Pull request by hustbeef**

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
We don't need so many MsgBoxes.

The rc file doesn't only contain pictures, it can contain anything.

**Comment by rexxitall** [comment]
i usually need only a few messageboxes / dialogs : msg, yes no, yes no cancel, input. but for sure i still neeed a vb6 like search and search and replace dialog ;) So can i obtain that you has made all the language strings or what its good for ?

**Comment by hustbeef** [comment]
> We don't need so many MsgBoxes.
> 
> The rc file doesn't only contain pictures, it can contain anything.
This only implemented checks for resource file keywords in imageManager. It cannot compile if the resource file contains `icon ICON "icon.ico"`, but it can still load into imageManager. 
`ERROR: Misplaced resource type, - icon`

**Comment by XusinboyBekchanov** [comment]
>So can i obtain that you has made all the language strings or what its good for ?

Yes, he linked the strings using a function like: ML("not loaded")
These strings are already in the lng files.

**Comment by rexxitall** [comment]
Cool :) So you are forced to add the string always :) I see "Jeanie" or "Babs" has some work around Xmas. I guess i will implement a function th heal my manual made mistakes as well by AI :) For those who do not know. The lng file goes into a sqlite DB and run on a first tsep trough a AI to get rought translated. Then is edited by Hand. The db is used to hold both version for any language. I dont want to correct the AI stuff again and again ;) BTW to add a AI Assistent is not that complicated. You create a JSON string with the format of ChatGPT or whatever , send it to the server via HTTP POST and get the result as JSON back. BABS does it with xhhtp.dll and JEANIE via AJAX direct in JS (She lives in a browser bottle). The main problem is to integrate it into the editor. Vause usually both girls are lazy and lie like Hell :) AI is a better typing helper. But around 80% is usable. so you need a function to compare and inject lines from the AI and the code. If you are interested we can discuss on discord and i can provide the code (VBS / VB6 /JS / VB.net). Which gives a head start. I am currently working again on my CAD stuff. Which means i have a lack of time to recode it to freebasic :/

**Pull request merged**
