### PR TITLE
Fixed:  The backcolor of description of properties in dark mode

### PR DESCRIPTION
**Pull request by hustbeef**

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
ForeColor is the same as DefaultForeColor, so there is no need to change it.
And in bright mode, BackColor does not coincide with DefaultBackColor, so when switching to dark mode, BackColor will not change. To fix this, we changed BackColor to DefaultBackColor before switching to dark mode. And when switching to bright mode, we changed BackColor to ButtonFace.

**Comment by hustbeef** [comment]
OK. Please go ahead and accept the post for further changes. The DefaultBackColor of RichTextBox is white and is displayed in the IDE when starting the IDE at the first time.

**Comment by hustbeef** [comment]
No. It is not fixed.  The DefaultBackColor of RichTextBox is white and is displayed in the IDE when starting the IDE at the first time. but it is OK after switch with "Darkmode"
image

image

**Comment by XusinboyBekchanov** [comment]
Have you downloaded this latest change to MyFbFramework?
https://github.com/XusinboyBekchanov/MyFbFramework/commit/ceea4b5e2436235050a352af96d0490e0902819e

**Comment by hustbeef** [comment]
NO. It is OK now after upgrade this.

**Pull request merged**
