### PR TITLE
Fixed: Fixed got the  type like WString * 100

### PR DESCRIPTION
**Pull request by hustbeef**
Add some change in TabWindow.bas

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
After Contains not need "If iIndex > -1 Then".

**Comment by XusinboyBekchanov** [comment]
Why put it in sometimes?
`If iIndex > 0 Then`

**Comment by XusinboyBekchanov** [comment]
Zero index is not taken into account?

**Comment by hustbeef** [comment]
This is a mistakes and could be remove it.

**Comment by hustbeef** [comment]
Yes. "If iIndex > -1 Then" is useless code in Tabwindow.bas. Alreday I remove it

**Pull request merged**
