### PR TITLE
Fixed：fixed the return Error and add language

### PR DESCRIPTION
**Pull request by hustbeef**
Add language to Command buttons only.

### CODE REVIEW

**Comment by rexxitall** [comment]
if you could finalize the language files i will do them near xmas :)

**Comment by hustbeef** [comment]
Welcome to the team! Please post your changes anytime. It's easy to use the Add-in tools ("Tools\LNGCreator.exe") to create the language files.

**Comment by rexxitall** [comment]
I already make the german an polish and some other translations ;) I prefer to use my own tools for that. You may ask XUSINGBOY, he know how i made it.

**Comment by XusinboyBekchanov** [comment]
>I already make the german an polish and some other translations ;) I prefer to use my own tools for that. You may ask XUSINGBOY, he know how i made it.

Yes, I know. You have created a tool to translate lng file.

>if you could finalize the language files i will do them near xmas :)

For this there must be a description of all the properties of the elements. I remember.

**Comment by rexxitall** [comment]
exactly :) Your brain works well. whatever control has as property, method whatever, whatever dialog spites out as text. nothing can be hardcoded. And its also a good idea to "fatten" the text areas. some languages needs more space then others to say the same. English is a bad choice cause it's short. Usually german need approximatly 10-20 percent more space to avoid bad abbreviations. :)

**Comment by XusinboyBekchanov** [comment]
>exactly :) Your brain works well. whatever control has as property, method whatever, whatever dialog spites out as text.

Adding a description to all properties is a to-do list:
https://github.com/XusinboyBekchanov/MyFbFramework/issues/8

>nothing can be hardcoded. And its also a good idea to "fatten" the text areas. some languages needs more space then others to say the same. English is a bad choice cause it's short. Usually german need approximatly 10-20 percent more space to avoid bad abbreviations. :)

We'll see about that too.

>But hey, you will get a nice german and maybee polish file and rough AI translations for all the others to give native speakers a head start ;)

Ok.

**Pull request merged**
