### PR TITLE
Add DeviceExplorer Example

### PR DESCRIPTION
**Pull request by chunmingwang**

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
Thanks.

**Comment by hustbeef** [comment]
All the icon disappears when moving from a high DPI (200%) screen to a low DPI (100%) screen. 
This happen if the icon is from memory or .dll files only?

image

**Comment by chunmingwang** [comment]
> the icon is from memory or .dll files only? （DeviceExplorer.vbp and USBView.vbp only？）

 the icons are from the setupapi.dll file.

**Comment by hustbeef** [comment]
I believe the code in "ImageList.SetImageSize" should be improved, as the new post bypasses resizing using the MFF code.

**Comment by chunmingwang** [comment]
> I believe the code in "ImageList.SetImageSize" should be improved, as the new post bypasses resizing using the MFF code.

My purpose on the new commit of DeviceExplorer is to achieve icon overlap display by using API imagelist with Control of imagelist

**Comment by XusinboyBekchanov** [comment]
>I believe the code in "ImageList.SetImageSize" should be improved, as the new post bypasses resizing using the MFF code.

Improved: ImageList on High DPI, Fixed: TreeView on High DPI:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/d982c40359aecf914eba0c9f1c78edbc52ae7386

**Comment by chunmingwang** [comment]
I will try to implement icon overlay display in the imagelist control

**Comment by XusinboyBekchanov** [comment]
>I will try to implement icon overlay display in the imagelist control

Very good idea, we are waiting for news from you.

**Comment by chunmingwang** [comment]
> I will try to implement icon overlay display in the imagelist control

I update DeviceExplorer example to achieve icon overlap display by using Control of imagelist

https://github.com/XusinboyBekchanov/VisualFBEditor/pull/723

**Comment by XusinboyBekchanov** [comment]
>I update DeviceExplorer example to achieve icon overlap display by using Control of imagelist

Thanks, I merged.

**Comment by hustbeef** [comment]
All the icon showing normal when moving from a high DPI (200%) screen to a low DPI (100%) screen. But the width of Line is different.

image  
image

**Comment by XusinboyBekchanov** [comment]
Fixed: Distance between pointer and icon when TreeView moves from High DPI to Low DPI:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/65f17b98eafe1daaa2bccd8ebc31e0cba475c707

**Pull request merged**
