### PR TITLE
Fixed: Multilingual text generation

### PR DESCRIPTION
**Pull request by hustbeef**

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
Let it be in English by default, then the user can select Chinese.

**Comment by hustbeef** [comment]
Yes. It is still displaying in English because there is no "chinese.lng" file. It will display Chinese if we create the "chinese.lng" file. Maybe we can try using the function "getenv" to retrieve the OS language setting later.

**Comment by XusinboyBekchanov** [comment]
>Maybe we can try using the function "getenv" to retrieve the OS language setting later.

Improved: CurLanguage property of Application takes the system language by default:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/f5fdef30ff428cbc3971be78c4bbfce7d7ae2efe

It is now possible not to specify a language.

**Comment by hustbeef** [comment]
That's awesome. We can remove the two lines ".CurLanguage = "english" from Templates as well.

**Comment by XusinboyBekchanov** [comment]
>That's awesome. We can remove the two lines ".CurLanguage = "english" from Templates as well.

Slightly changed:

Added: Language property to Application, Added: Language function to Sys namespace:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/9ca51f5d904676687c4ad7c548fc56a3af561abf

Updated: Form templates:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/96b508a9e9e74002a739d0fbef7b14566951d4d7

**Comment by XusinboyBekchanov** [comment]
Now you can use the system language like this:
```
'#Region "Form"
	#if defined(__FB_MAIN__) AndAlso Not defined(__MAIN_FILE__)
		#define __MAIN_FILE__
		#ifdef __FB_WIN32__
			#cmdline "Form1.rc"
		#endif
		Const _MAIN_FILE_ = __FILE__
	#endif
	#include once "mff/Form.bi"
	#include once "mff/Sys.bi"
	
	Using My.Sys.Forms
	
	Type Form1Type Extends Form
		Declare Constructor
		
	End Type
	
	Constructor Form1Type
		#if _MAIN_FILE_ = __FILE__
			With App
				.CurLanguagePath = ExePath & "/Languages/"
				.CurLanguage = My.Sys.Language
			End With
		#endif
		' Form1
		With This
			.Name = "Form1"
			.Text = "Form1"
			.Designer = @This
			.SetBounds 0, 0, 350, 300
		End With
	End Constructor
	
	Dim Shared Form1 As Form1Type
	
	#if _MAIN_FILE_ = __FILE__
		App.DarkMode = True
		Form1.MainForm = True
		Form1.Show
		App.Run
	#endif
'#End Region
```

**Comment by hustbeef** [comment]
My.SYS.Language not working? No defined. The default value of FLanguage in Appication.bas is NULL also.

**Comment by XusinboyBekchanov** [comment]
Here it is shown:
image

**Comment by XusinboyBekchanov** [comment]
It takes from Form1.rc

**Comment by XusinboyBekchanov** [comment]
My.Sys.Language works:
image

**Comment by hustbeef** [comment]
Yes. I forgot add the code `#include once "mff/sys.bi"`

**Comment by hustbeef** [comment]
Now it's time to eliminate "ML" from text in design mode.

**Pull request merged**
